name: order
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  intl: ^0.18.1
  provider: ^6.1.1
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
